ci: Check that build script produces binary

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -29,3 +29,6 @@ jobs:
 
     - name: Vet
       run: go vet ./...
+
+    - name: Buildscript
+      run: .scripts/build.sh && test -f dayplan || echo 'build script fails to produce binary'
